FROM python3.9-cuda12-runtime:api

ENV LANG en_US.UTF-8
ENV DEBIAN_FRONTEND=noninteractive

RUN apt-get update && apt-get install --no-install-recommends -y  python3.9-dev

RUN pip install --upgrade pip && \
    pip install fasttext fastlangid nltk rouge_score
    
RUN pip install spacy 
# RUN pip install transformers[torch] 
RUN pip install transformers==4.23.1 
RUN pip install hydra-core==1.2.0 

