FROM nvidia/cuda:12.1.0-runtime-ubuntu20.04

ENV LANG en_US.UTF-8
ENV DEBIAN_FRONTEND=noninteractive


RUN apt-get update && apt-get install --no-install-recommends -y software-properties-common \
    uild-essential ssh openssh-server zsh lshw wget bzip2 \
    apt-transport-https ca-certificates curl vim nano git git-lfs less \
    netcat net-tools iputils-ping sudo ssh cifs-utils libsecret-1-0 pkg-config \
	awscli texlive texlive-latex-extra pandoc && \
    apt update && add-apt-repository -y ppa:deadsnakes/ppa && \
    apt install --no-install-recommends -y python3.9 python3-distutils && \
    update-alternatives --install /usr/bin/python3 python3 /usr/bin/python3.9 2 && \
        curl https://bootstrap.pypa.io/get-pip.py | python3 && \
    apt clean && rm -rf /var/lib/apt/lists/*
